//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kanji
    {
        public int ID { get; set; }
        public string Word { get; set; }
        public string Onyomi { get; set; }
        public string Kunyomi { get; set; }
        public string Mean { get; set; }
        public string Voc1 { get; set; }
        public string Voc2 { get; set; }
        public string Voc3 { get; set; }
        public string Voc4 { get; set; }
        public string Voc5 { get; set; }
        public string Hira1 { get; set; }
        public string Hira2 { get; set; }
        public string Hira3 { get; set; }
        public string Hira4 { get; set; }
        public string Hira5 { get; set; }
        public string Mean1 { get; set; }
        public string Mean2 { get; set; }
        public string Mean3 { get; set; }
        public string Mean4 { get; set; }
        public string Mean5 { get; set; }
        public string Level { get; set; }
        public Nullable<int> GroupSetID { get; set; }
        public Nullable<bool> IsLiked { get; set; }
    }
}
