//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocabulary
    {
        public int ID { get; set; }
        public string Hiragana { get; set; }
        public string Kanji { get; set; }
        public string Mean { get; set; }
        public int LessonID { get; set; }
        public string Type { get; set; }
    }
}
